version: '3.8'
services:
  server:
    build: ./server
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=hndb_1
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  
  client:
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=http://localhost:3000
    ports:
      - "3001:80"
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hndb_1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
