name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.1.0]

    steps:
    - uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Install server dependencies
    - name: Install server dependencies
      run: npm ci
      working-directory: ./server

    # Lint server code
    - name: Lint server
      run: npm run lint
      working-directory: ./server

    # Run server tests
    - name: Test server
      run: npm test
      working-directory: ./server
